version: "3"
services:
  mariadb-001:
    build: ../docker/mariadb/
    container_name: mariadb-001
    hostname: mariadb-001
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ../volumes/db/mariadb-001/data:/var/lib/mysql
      - ../volumes/db/mariadb-001/log:/var/log/mysql
      - ../volumes/db/mariadb-001/conf/my.cnf:/etc/mysql/my.cnf
      - ../volumes/db/mariadb-001/db-init-files/:/docker-entrypoint-initdb.d/
    networks:
      - mdbbridge

  mariadb-002:
    build: ../docker/mariadb/
    container_name: mariadb-002
    hostname: mariadb-002
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ../volumes/db/mariadb-002/data:/var/lib/mysql
      - ../volumes/db/mariadb-002/log:/var/log/mysql
      - ../volumes/db/mariadb-002/conf/my.cnf:/etc/mysql/my.cnf
      - ../volumes/db/mariadb-002/db-init-files/:/docker-entrypoint-initdb.d/
    networks:
      - mdbbridge

  mariadb-003:
    build: ../docker/mariadb/
    container_name: mariadb-003
    hostname: mariadb-003
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ../volumes/db/mariadb-003/data:/var/lib/mysql
      - ../volumes/db/mariadb-003/log:/var/log/mysql
      - ../volumes/db/mariadb-003/conf/my.cnf:/etc/mysql/my.cnf
      - ../volumes/db/mariadb-003/db-init-files/:/docker-entrypoint-initdb.d/
    networks:
      - mdbbridge
      
networks:
  mdbbridge:
    #external: true
    driver: bridge
